# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  reconnect: false
  host: localhost
  port: 5432

development:
  adapter: postgresql
  database: 
  username: postgres
  password: test